version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
      time: "05:00"
      timezone: Asia/Shanghai
    ignore:
      - dependency-name: semantic-release
        versions:
          - ">= 21.0.1"
      - dependency-name: "@commitlint/cli"
        versions:
          - ">= 19.0.0"
      - dependency-name: "@commitlint/config-conventional"
        versions:
          - ">= 19.0.0"
      - dependency-name: "file-type"
        versions:
          - ">= 17.0.0"
      - dependency-name: "query-string"
        versions:
          - ">= 8.0.0"
      - dependency-name: "p-limit"
        versions:
          - ">= 4.0.0"
      - dependency-name: "parse-torrent"
        versions:
          - ">= 10.0.0"
