version: "3"

services:
  server:
    # build: .
    image: ${DOCKER_IMAGE:-caomeiyouren/rss-impact-server}
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      TIMEOUT: 10000
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-123456}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      SESSION_SECRET: ${SESSION_SECRET:-RSS_IMPACT}
      RESOURCE_DOWNLOAD_PATH: './data/download'
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
