version: "3"

services:
  server:
    # build: .
    container_name: 'rss-impact-server'
    image: ${DOCKER_IMAGE:-caomeiyouren/rss-impact-server}
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      TIMEOUT: 60000
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-123456}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      SESSION_SECRET: ${SESSION_SECRET:-RSS_IMPACT}
      RESOURCE_DOWNLOAD_PATH: './data/download'
      # 启用跨域。如果前端和后端部署在不同域名下，需要跨域时，配置该项。
      # ENABLE_ORIGIN_LIST: 'http://localhost:3000,http://127.0.0.1:3000'
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
