name: Publish Docker Image

on:
  push:
    branches:
      - master

# 仅取消针对当前工作流正在进行的作业或运行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Get short commit hash
        run: echo "TAG=${GITHUB_SHA::8}" >>${GITHUB_ENV}
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REPO }}:${{ env.TAG }},${{ env.REPO }}:latest
      - name: Deploy to Jenkins
        run: curl -X POST -L --user ${{ secrets.JENKINS_TOKEN }} ${{ secrets.JENKINS_URL }}/buildWithParameters?token=${{ JENKINS_JOB_TOKEN }}&DOCKER_IMAGE=${{ env.REPO }}:${{ env.TAG }}
