name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run lint:md
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run test:e2e
      - run: pnpm run test:cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
